### ISSUE TITLE
Add Google Analytics for tracking

### ISSUE THREAD

**Issue by tulu** [tulu/chrome-extension-npm-faves#21]
Add GA script to track extension usage:

- [x] Review how to and add the script
- [x] Track pageviews
    - [x] pop up
    - [x] options
- [x] Track events
    - [x] content button clicks
    - [x] pop up navigation click
    - [x] pop up remove click
